#!/bin/bash

# Build docker image
git clone https://github.com/madha14/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t madha14/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles
